name = "Compliance Banner"
type = "theme_app_extension"
identifier = "com.ithappens.compliance-banner"
version = "0.1.0"
description = "A theme app extension that displays a compliance banner on storefront pages to ensure pricing compliance with Norwegian regulations."
